
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: josh
  password: admin

development:
  <<: *default
  database: champ_dev

test:
  <<: *default
  database: champ_test

production:
  <<: *default
  database: champ_prod
